version: "3.6"

services:
  eiffelactory:
    image: eiffelactory:latest
    volumes:
      - type: bind
        source: ./conf
        target: /app/conf
    networks:
      - eiffelactorynet

networks:
  eiffelactorynet:
